version: "3"

services:
  api:
    container_name: remix_api
    build:
      context: .
      dockerfile: DockerfilePython
    command: sh -c "cd api && uvicorn main:app --reload"
    volumes:
      - ./api:/remix/api
    tty: true
    ports:
      - 8000:8000
  app:
    container_name: remix_app
    build:
      context: .
      dockerfile: DockerfileNode
    command: sh -c "cd remix-app && npm run dev"
    volumes:
      - .:/remix
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - api
